<?php
/**
 * Do not edit this file directly.  You can copy this file to your theme directory
 * in woocommerce-pay-per-post/pageview-status.php
 *
 *
 * $user_info = Array
(
    [last_purchase_date] => Carbon\Carbon Object
        (
            [date] => 2018-08-10 14:57:27.000000
            [timezone_type] => 3
            [timezone] => UTC
        )

    [end_date] => Carbon\Carbon Object
        (
            [date] => 2019-08-10 14:57:27.000000
            [timezone_type] => 3
            [timezone] => UTC
        )

    [total_page_views] => 44
)
 *
 *
 * $number_of_allowed_pageviews = integer of allowed page views
 *
 */

?>
<div class="wc-ppp-pageview-status-container">
    <h4><?php esc_attr_e( 'Order Information', 'wc_pay_per_post' ); ?></h4>
    <ul>
        <li><strong><?php esc_attr_e( 'Order Date', 'wc_pay_per_post' ); ?></strong>: <?php echo $user_info['last_purchase_date']->toFormattedDateString(); ?></li>
        <li><strong><?php esc_attr_e( 'Page Views', 'wc_pay_per_post' ); ?></strong>: <?php echo $user_info['total_page_views']; ?> <?php esc_attr_e( 'out of', 'wc_pay_per_post' ); ?> <?php echo $number_of_allowed_pageviews; ?></li>
    </ul>
</div>