<?php
	/**
	 * Do not edit this file directly.  You can copy this file to your theme directory
	 * in woocommerce-pay-per-post/shortcode-remaining.php
	 * The $remaining variable is a WP Posts Object of not yet purchased posts.
	 */

?>
<?php if ( count( $remaining ) > 0 ) : ?>
	<div class="wc-ppp-remaining-container">
		<ul>
			<?php foreach ( $remaining as $post ) : ?>
				<li><a href="<?php echo esc_html( get_permalink( $post->ID ) ); ?>"><?php echo esc_html( $post->post_title ); ?></a></li>
			<?php endforeach; ?>
		</ul>
	</div>
<?php endif; ?>
